### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by appsforartists** [chuangzhu/nixpkgs-gnome-mobile#1]
I appreciate the work you've put into this and I'd like to contribute. I know this sounds silly, but unfortunately, we're only allowed to contribute to projects with lawyer-vetted licenses, and the [WTFPL is explicitly not one](https://opensource.google/documentation/reference/patching#forbidden).

Would you be amenable to relicensing under a more conventional license (MIT, BSD, and Apache are all good choices)?

**Comment by chuangzhu** [comment]
done

**Comment by appsforartists** [comment]
Thanks.

I was originally going to [package `force-phone-mode`](https://github.com/appsforartists/nixpkgs/commit/8f8aa6b427e4fca1f96a29707fa6882ceeaf8c00) for this repo.  Then I realized it's a better fit for [a nixpkgs branch](https://github.com/appsforartists/nixpkgs/tree/appsforartists), and then I later realized it's not even usable for me because [the Steam keyboard doesn't work in mobile GNOME](https://gitlab.gnome.org/verdre/mobile-shell/-/issues/33).
